#
# default pronouns that will be used for anyone who has not yet set a pronoun, or who has had their pronouns cleared
default-pronouns: "they-them"
# should players be allowed to create custom pronouns?
allow-custom-pronouns: false
#available save types: PDC, MYSQL
save-type: PDC
mysql:
  ip: "localhost:3306"
  name: pronouns
  username: username1
  password: badpassword!


