name: SimplePronouns
version: '${project.version}'
main: simplexity.simplepronouns.SimplePronouns
api-version: '1.20'
commands:
  pronouns:
    permission: pronouns
    description: Base command for plugin functionality
  spreload:
    permission: pronouns.reload
    description: Reloads the plugin
permissions:
  pronouns.set:
    description: Allows the user to set their pronouns
    default: op
  pronouns.list:
    description: Allows the user to see a list of all pronouns
    default: op
  pronouns.get:
    description: Allows the user to see what pronouns other people are using
    default: op
  pronouns.clear:
    description: Allows the user to remove their pronouns
    default: op
  pronouns.custom:
    description: Allows the user to set custom pronouns for themselves
    default: op
  pronouns.admin:
    description: Allows the user to use administrative commands
    default: op
  pronouns.admin.set:
    description: Allows the user to set other users' pronouns
    default: op
  pronouns.admin.clear:
    description: Allows the user to clear other users' pronouns
    default: op
  pronouns.admin.custom:
    description: Allows the user to set custom pronouns on other users
    default: op
  pronouns.reload:
    description: Allows the user to reload the plugin
    default: op
softdepend:
  - PlaceholderAPI
